### ISSUE TITLE
Can I easily parallelize the search with multiple GPUs?

### ISSUE THREAD

**Issue by kwmaeng91** [google/pyglove#11]
Hi, experts.
I am really enjoying PyGlove!
I have a question regarding accelerating the search. If I have multiple GPUs, does PyGlove supports parallelizing the search easily?
If so, it would be great if you can give me any pointers.

Thank you!

**Comment by daiyip** [comment]
Good question, right now the OSS PyGlove only bundle with a 'in-memory' tuning backend, but we do plan to release a tuning backend for distributed tuning based on [Vizier](https://github.com/google/vizier), so users can switch between backends in a single line of code. We will also document how to build tuning backend later.

**Comment by xingyousong** [comment]
Hi @kwmaeng91, OSS Vizier is now available as a backend for PyGlove: https://oss-vizier.readthedocs.io/en/latest/advanced_topics/pyglove/vizier_as_backend.html
