### ISSUE TITLE
Having tied parameters?

### ISSUE THREAD

**Issue by t-schn** [google/pyglove#120]
Hi, 

I'm having issues figuring out how to tie hyperparameters together. What I would like to have is something like

`activation_1 = ActivationLayer(pg.one_of(["sigmoid", "relu"]))`
`activation_2 = ActivationLayer(pg.one_of(["sigmoid", "relu"]))`
`space = pg.List([Weights(), activation_2, Weights(), activation_1, Weights(), activation_1, Weights(), activation_2]) `

where activation_1 and activation_2 change together. However, because it is passed by value, all of these end up being separate. Any ideas on how to achieve my desired outcome?

**Comment by t-schn** [comment]
@daiyip: Thanks, that helps a lot! Thinking more about these different paradigms, I think tied hyperparameters are only a special case of branching (if-then-else) which seems much harder to solve. For example, Optuna has the following example:
```python
def objective(trial):
    classifier_name = trial.suggest_categorical("classifier", ["SVC", "RandomForest"])
    if classifier_name == "SVC":
        svc_c = trial.suggest_float("svc_c", 1e-10, 1e10, log=True)
        ...
    else:
        rf_max_depth = trial.suggest_int("rf_max_depth", 2, 32, log=True)
        ...
```

Now, I could reproduce this with the dynamic evaluation, but this would not be compatible with genetic programming since the `.trace()` method wouldn't collect all branches. I could use nested functors to make this happen, too, but this would not allow me to use one genetic optimization loop.

**Comment by daiyip** [comment]
By the way, for nested functors, you could do:

```python
@pg.symbolize
def svc_classifier(...):
   ...

@pg.symbolize
def random_forest(...):
  ...

@pg.symbolize(
def solution(classifier, ...):
   ret = classifier()
   ...

ss = solution(
     pg.oneof([
         svc_classifier(pg.floatv(1e-10, 1e10, scale='log')),
         random_forest(pg.oneof(range(2, 32))
    ]))

for s, f in pg.sample(ss, ...):
   reward = s()
   f(reward)
```

**Comment by t-schn** [comment]
@daiyip : Thanks a lot! I think what I was confused about earlier was supporting if statements in the dynamic evaluation mode. This doesn't work as tracing wouldn't be able to discover all paths. The proper way to do it is with oneof as you described. Here is a self-contained example illustrating the flexibility of the dynamic mode (hopefully useful for other people):

```python
import pg

@pg.symbolize
class svc_classifier:
    def __init__(self, r):
        self._r = r
        
@pg.symbolize      
class random_forest(svc_classifier):
    pass

def foo():
    classifier = lambda: pg.oneof([
        lambda: svc_classifier(pg.one_of(range(3,5), name='hello')),
        lambda: random_forest(pg.one_of(range(2, 3), name='rf_max_depth'))
    ], name='classifier')
    repetitions = pg.one_of([2, 5], name="length")
    chain = pg.permutate([classifier, lambda: 1])*repetitions
    return chain

examples = []
for x in pg.iter(pg.hyper.trace(foo)):
    with x():
        examples.append(foo())
        
print(examples)
```
