### ISSUE TITLE
pg.diff between two identical objects

### ISSUE THREAD

**Issue by D-X-Y** [google/pyglove#184]
```
import pyglove as pg

class A(pg.Object):
    x: str

print(pg.diff(A(x="1"), A(x="2")))

print(pg.diff(A(x="1"), A(x="1")))
```

The later one outputs the entire `A`, shouldn't it just produce `A()`?

**Comment by daiyip** [comment]
Good question. It might seems confusing to return the same object itself, the mental model was to simulate a diff tool, which has the left side and the right side - when both sides are the same, they appear to be the same content, which is the object itself.

I think a better treatment is that when `pg.diff(A(x='1'), A(x='1'))` (mode='diff'), it should return None, and when the mode='same' or 'both', it returns the object itself. Does this make sense? I will be sending out a PR for this.

**Comment by D-X-Y** [comment]
I would prefer to be consistent with non-identical case.
For example, it make sense to me to see `A(IDENTICAL)` instead of `None` because the later case need additional handling on `None`.

**Comment by daiyip** [comment]
It took me some revisit to realize that current behavior is actually correct. 

The `pg.diff(A(x='1', A(x='1'))` returns `pg.Diff(A(x='1'), A(x='1'))` ('D' is capitalized) instead of `A(x='1')`, though `str(pg.Diff)` uses the str form of the value if `left` and `right` are identical. You can simply apply a `bool` operator on `pg.Diff` (e.g. `bool(pg.Diff(...)`) or use predicate like `if not pg.diff(...)`.

**Comment by daiyip** [comment]
Okay, I tuned the behavior a little bit - now `pg.diff(A(x='1'), A(x='1'))` (mode='diff' by default) will return `pg.Diff(left=pg.Diff.MISSING, right=pg.Diff.MISSING)` whose representation or string is 'No diff'. For `pg.diff(A(x='1', A(x='1'), mode='same')`, it will return `pg.Diff(left=A(x='1'), right=A(x='1'))`, which will print as `A(x='1')`. 

Please see [Commit# e31fa99](https://github.com/google/pyglove/commit/e31fa995e11d2de5e6bf0ca36a9364aac3e8a92a)) for details.

**Comment by D-X-Y** [comment]
This makes a lot of sense to me, thanks for your quick fix!
