### ISSUE TITLE
Can we disable __init__ for the users?

### ISSUE THREAD

**Issue by D-X-Y** [google/pyglove#198]
PyGlove disabled a few functions for the users, such as `__init__` because some of its magics rely on hacking the built-in python class functions. However, if a user does not know it and still write a `__init__` function as usual, PyGlove does not raise any error and just quietly pass the codes and failed at somewhere later.

Therefore, could we explicitly raise some errors right after the user define a PG class with __init__?

**Comment by daiyip** [comment]
You got it in [v0.4.2](https://github.com/google/pyglove/releases/tag/v0.4.2).

**Comment by D-X-Y** [comment]
wow, nice! Let me have a try!
