### ISSUE TITLE
Question on Type Annotation and Docstring

### ISSUE THREAD

**Issue by D-X-Y** [google/pyglove#202]
Does the following two things perform differently in pyglove?
```
class Foo:
    field_a: int = 42
    "field_a docstring"
```
and
```
class Foo:
    field_a: Annotated[int, "field_a docstring"] = 42
```

**Comment by daiyip** [comment]
PyGlove only supports the latter syntax. For the former one, the `field_a string` is not associated with the field.

**Comment by D-X-Y** [comment]
Yeah, it seems that the latter syntax is the official way of attribute annotation. Because the second `args` can go far beyond the string type, it was originally designed to attach some metadata in the annotation.

**Comment by daiyip** [comment]
I know :-) In my opinion `Annotated` is more scalable in providing extra information for a field, based on which we can easily support value spec & field metadata in near future. These features are already part of `pg.members`.

We may consider support the "official" attribute annotation if our fellow users prefer this way, although I personally don't like it for its poorer readability and scalability. But let me know if you are in a urgent need.

**Comment by D-X-Y** [comment]
lol, no urgent need. The external IDEs do not view `Annotated[.., x]`'s s as annotation and thus will ignore them, just a heads up on the incompatibility of those common softwares vs. the practice in PG~

**Comment by daiyip** [comment]
Good to know. 

It seems the "former" form of field annotation (a new line of string following the field definition) was proposed in [PEP-224](https://peps.python.org/pep-0224/) but got rejected. So maybe we should wait a bit see the necessity of this support.
