### ISSUE TITLE
Lack of type parameters to `Callable`

### ISSUE THREAD

**Issue by jvican** [google/pyglove#51]
Hey there! I'm excited about this project. I've been wanting metaprogramming capabilities like the ones pyglove supports in Python for a long time, and I'm trying this out for a project at work. I'm lurking right now in the codebase and playing with it as a prototype.

During a bit of my exploration, I've noticed that `pg.typing.Callable` doesn't take any type parameters. This is confusing as the default Python typing does - is there a reason for this? Could we add type parameters to be more precise when defining callables in `pg.members`?

**Comment by jvican** [comment]
Actually, nevermind, just found out that `pg.typing.Callable` enables us to pass the parameters as values, which I guess is consistent with the rest of the pyglove API (e.g. `pg.typing.Dict`). So I guess my question now would be, is there a reason why we couldn't _also_ support type parameters a la `pg.typing.Callable[T, R]` just like one can do in Python, for cases where we don't want to make `T` and `R` configurable?

**Comment by daiyip** [comment]
I am glad that you find PyGlove useful. 

We did have previous asks for making `pg.typing.XXX` more like `typing.XXX` so they can be more friendly to PyType users, and it's definitely doable. In my mind, an ideal solution would be providing a transparent PyType <-> PyGlove typing conversion with some decorators, I hope we will get into this before long. Thanks for the suggestions.

**Comment by jvican** [comment]
Thanks for the answer! I might find the time to work on this transparent PyType <-> Pyglove conversion. Are you accepting contributions now?

**Comment by daiyip** [comment]
Thanks for the offering. I am sorry that we are not ready for contributions yet - but I will find time for putting this to work. Created #55 for tracking this feature.

**Comment by jvican** [comment]
Cool, yeah please do let me know when you're ready and have configured CLA signing and all of that. I'd love to send a few contributions.

**Comment by daiyip** [comment]
That sounds good. Looking forward to your future contributions!
