### ISSUE TITLE
Questions about the generator algorithms.

### ISSUE THREAD

**Issue by kwmaeng91** [google/pyglove#8]
Hi, experts.
I am very interested about PyGlove and want to try it out for my NAS project.
However, I am not sure what is a reasonable way to generate candidates other than using Random().

(1) The natsbench.py code uses pg.generators.PPO(). However, PPO is not defined in the codebase. How can I use PPO()?
(2) nasbench.py uses pg.evolution.regularized_evolution(), which is defined. However, the mutator is defined as follows, which I do not understand what it means

```
mutator=(
            pg.evolution.mutators.Uniform(
                where=node_selector(hints=OP_HINTS))         # pylint: disable=no-value-for-parameter
            >> pg.evolution.mutators.Uniform(
                where=node_selector(hints=EDGE_HINTS)) ** 3  # pylint: disable=no-value-for-parameter
        )
```
        
Can you explain (1) how I can use PPO() and/or (2) how I can define the mutator effectively (what does the above code do)?

Thank you for your help.

**Comment by daiyip** [comment]
Thanks for your interest in PyGlove! 

Good catch on the missing `pg.generators.PPO` from 'natsbench.py`, which is not available in OSS PyGlove yet - I will remove its occurrences to avoid confusion. At the moment, we encourage PyGlove users to use evolutionary algorithms for NAS, which has been effective and widely used in many NAS literatures (e.g. https://arxiv.org/abs/1802.01548, https://arxiv.org/abs/2101.03958).  

PyGlove provides a map-reduce style expression to create evolutionary algorithms, `>>` here means to pipeline, and `**` means to apply a mutator multiple times. So the following composite mutator means to perform a mutation on a randomly selected op, followed by 3 mutations on randomly selected edges.

```
mutator=(
            pg.evolution.mutators.Uniform(
                where=node_selector(hints=OP_HINTS))         # pylint: disable=no-value-for-parameter
            >> pg.evolution.mutators.Uniform(
                where=node_selector(hints=EDGE_HINTS)) ** 3  # pylint: disable=no-value-for-parameter
        )
```

We are still working on the documentation for PyGlove, hopefully it will be released soon. Before that, please refer to the [docstr of `Operation` class](https://github.com/google/pyglove/blob/9a39e01d6ff146e1e6b48b38fe848129a8a33e4b/pyglove/generators/evolution/base.py#L133
) for chain-able operators supported.

**Comment by kwmaeng91** [comment]
Thank you so much for the quick reply, @daiyip! I have one more question. If I do not pass any parameters to Uniform() as in natsbench.py, what is the default behavior?

**Comment by daiyip** [comment]
If `Uniform` is specified without an argument, the mutation candidates are all the decision points in the search space (that is op + edge combined). In that case, the formula above is equivalent to  
```
   pg.evolution.mutators.Uniform() 
   >>  pg.evolution.mutators.Uniform()
   >>  pg.evolution.mutators.Uniform()
   >>  pg.evolution.mutators.Uniform()
```
or simply `pg.evolution.mutators.Uniform() ** 4`.
